/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.is.crudproject.viewdbswing;

import java.awt.HeadlessException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.is.crudproject.dbconfig.ConnectionManager;
import org.itenas.is.crudproject.model.Pemilik_ps;
import org.itenas.is.crudproject.services.CrudService;
import org.itenas.is.crudproject.servicesdbimpl.ControllerPeminjam;
import org.itenas.is.crudproject.model.Peminjam;
import org.itenas.is.crudproject.servicesdbimpl.ControllerPengembalian;
import org.itenas.is.crudproject.servicesdbimpl.ControllerPs;

/**
 *
 * @author riyann
 */
public class ViewPengembalian extends javax.swing.JFrame {
      private CrudService<Peminjam> peminjamCrudService;
   
    public ViewPengembalian() {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_pengembalian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_waktu_tenggat = new javax.swing.JTextField();
        txt_tgl_pengembalian = new javax.swing.JTextField();
        txt_total_denda = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_pengembalian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_peminjaman = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_tgl_pengambilan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_durasi_sewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_nama_ps = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_total_harga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(890, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(890, 600));

        table_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama Penyewa", "No telp", "alamat", "ps", "Durasi sewa hari", "tgl mulai", "tgl tenggat", "harga perhari", "total harga", "tgl pengembalian", "Denda"
            }
        ));
        table_pengembalian.setRequestFocusEnabled(false);
        table_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_pengembalian);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Waktu Tenggat");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Total denda");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("tgl pengembalian");

        txt_waktu_tenggat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_waktu_tenggatActionPerformed(evt);
            }
        });

        txt_tgl_pengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tgl_pengembalianKeyReleased(evt);
            }
        });

        txt_total_denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_dendaActionPerformed(evt);
            }
        });
        txt_total_denda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_total_dendaKeyReleased(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("No. ID");

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setRequestFocusEnabled(false);

        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });

        btn_stok.setText("Stok Barang");
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_peminjaman.setText("Peminjaman");
        btn_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peminjamanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENGEMBALIAN PS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Nama Penyewa");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("No telp");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Alamat");

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("tanggal mulai");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("durasi sewa");

        txt_durasi_sewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_durasi_sewaKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel13.setText("Nama Ps");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel14.setText("harga perhari");

        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargaKeyReleased(evt);
            }
        });

        txt_total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_hargaActionPerformed(evt);
            }
        });
        txt_total_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_total_hargaKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel15.setText("Total harga");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(137, 137, 137)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_tgl_pengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_durasi_sewa, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(txt_waktu_tenggat))))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(txt_total_harga, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_nama_ps)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_total_denda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_tgl_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_nama_ps, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(txt_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_tgl_pengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tgl_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_waktu_tenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_durasi_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_total_denda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_waktu_tenggatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_waktu_tenggatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_waktu_tenggatActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        emptyField();
       
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
         peminjamCrudService = new ControllerPeminjam(new ConnectionManager());

    // Ambil ID Peminjaman dari input
    String id = txt_search.getText().trim();

    // Validasi apakah ID kosong
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Peminjaman harus diisi sebelum menghapus data!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Konfirmasi penghapusan data
    int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            // Hapus data berdasarkan ID dan cek keberhasilannya
            boolean isDeleted = peminjamCrudService.delete(Integer.parseInt(id));
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadData(); // Refresh tabel setelah penghapusan
                emptyField(); // Kosongkan input field
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus. ID tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new ViewLogIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    // TODO add your handling code here:
            try {
        peminjamCrudService = new ControllerPeminjam(new ConnectionManager());

        // Validasi input ID
        String idPeminjamanStr = txt_search.getText().trim();
        if (idPeminjamanStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id_peminjaman;
        try {
            id_peminjaman = Integer.parseInt(idPeminjamanStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi input data
        if (txt_nama.getText().trim().isEmpty()
                || txt_notelp.getText().trim().isEmpty()
                || txt_alamat.getText().trim().isEmpty()
                || txt_tgl_pengambilan.getText().trim().isEmpty()
                || txt_durasi_sewa.getText().trim().isEmpty()
                || txt_nama_ps.getText().trim().isEmpty()
                || txt_harga.getText().trim().isEmpty()
                || txt_total_harga.getText().trim().isEmpty()
                || txt_tgl_pengembalian.getText().trim().isEmpty()
                || txt_total_denda.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ambil data dari input
        String nama = txt_nama.getText().trim();
        String no_telp = txt_notelp.getText().trim();
        String alamat = txt_alamat.getText().trim();
        String ps = txt_nama_ps.getText().trim();
        double harga = Double.parseDouble(txt_harga.getText().trim());
        double total_biaya = Double.parseDouble(txt_total_harga.getText().trim());
        int durasi = Integer.parseInt(txt_durasi_sewa.getText().trim());
        double total_Denda = Double.parseDouble(txt_total_denda.getText().trim());

        // Konversi tanggal
        LocalDate tglPengambilan = LocalDate.parse(txt_tgl_pengambilan.getText().trim());
        LocalDate tglTenggat = tglPengambilan.plusDays(durasi);
        LocalDate tglPengembalian = LocalDate.parse(txt_tgl_pengembalian.getText().trim());

        // Membuat objek peminjam
        Peminjam peminjam = new Peminjam();
        peminjam.setNama_Penyewa(nama);
        peminjam.setNo_Telp(no_telp);
        peminjam.setAlamat(alamat);
        peminjam.setPs(ps);
        peminjam.setDurasi_Hari(durasi);
        peminjam.setTgl_Pengambilan(tglPengambilan.toString());
        peminjam.setTgl_Tenggat(tglTenggat.toString());
        peminjam.setHarga(harga);
        peminjam.setTotal_Biaya(total_biaya);
        peminjam.setTgl_pengembalian(tglPengembalian.toString());
        peminjam.setTotal_denda(total_Denda);

        // Lakukan update data
        peminjamCrudService.update(id_peminjaman, peminjam);

        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadData(); // Memuat ulang data ke tabel
        emptyField(); // Mengosongkan field input

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa kembali input Durasi atau Harga.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peminjamanActionPerformed
        // TODO add your handling code here:
        new ViewPeminjaman().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_peminjamanActionPerformed

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        // TODO add your handling code here:
        new ViewPengembalian().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
        new ViewStok().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_stokActionPerformed

    private void table_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pengembalianMouseClicked
            try {
         // Deklarasi variabel
         String nama_penyewa, alamat, no_telp, tgl_pengambilan, tgl_tenggat, nama_ps, tgl_pengembalian;
         double hargaPerHari, total_Harga, total_Denda;
         int durasi, id_peminjaman;

         // Ambil baris yang dipilih di tabel
         int row = table_pengembalian.getSelectedRow();

         // Parsing nilai dari tabel menggunakan metode bantu
         id_peminjaman = parseInteger(table_pengembalian.getValueAt(row, 0));
         nama_penyewa = parseString(table_pengembalian.getValueAt(row, 1));
         no_telp = parseString(table_pengembalian.getValueAt(row, 2));
         alamat = parseString(table_pengembalian.getValueAt(row, 3));
         nama_ps = parseString(table_pengembalian.getValueAt(row, 4));
         durasi = parseInteger(table_pengembalian.getValueAt(row, 5));
         tgl_pengambilan = parseString(table_pengembalian.getValueAt(row, 6));
         tgl_tenggat = parseString(table_pengembalian.getValueAt(row, 7));
         hargaPerHari = parseDouble(table_pengembalian.getValueAt(row, 8));
         total_Harga = parseDouble(table_pengembalian.getValueAt(row, 9));
         tgl_pengembalian = parseString(table_pengembalian.getValueAt(row, 10));
         total_Denda = parseDouble(table_pengembalian.getValueAt(row, 11));

         // Tampilkan nilai pada form
         txt_search.setText(String.valueOf(id_peminjaman));
         txt_search.setEnabled(false);
         txt_nama.setText(nama_penyewa);
         txt_notelp.setText(no_telp);
         txt_alamat.setText(alamat);
         txt_waktu_tenggat.setText(tgl_tenggat);
         txt_tgl_pengambilan.setText(tgl_pengambilan);
         txt_tgl_pengembalian.setText(tgl_pengembalian);
         txt_durasi_sewa.setText(String.valueOf(durasi));
         txt_nama_ps.setText(nama_ps);

         // Format harga dan total harga dengan titik sebagai pemisah desimal
         txt_harga.setText(String.format("%.2f", hargaPerHari).replace(',', '.'));
         txt_total_harga.setText(String.format("%.2f", total_Harga).replace(',', '.'));
         txt_total_denda.setText(String.format("%.2f", total_Denda).replace(',', '.'));
     } catch (Exception e) {
         // Tangani kesalahan jika ada
         JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
     }

    }//GEN-LAST:event_table_pengembalianMouseClicked

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_durasi_sewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_durasi_sewaKeyReleased
        // TODO add your handling code here:
        //calculateTotalHarga();
        hitungDenda();
    }//GEN-LAST:event_txt_durasi_sewaKeyReleased

    private void txt_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyReleased
        // TODO add your handling code here:
        //calculateTotalHarga();
    }//GEN-LAST:event_txt_hargaKeyReleased

    private void txt_total_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_hargaKeyReleased
        //calculateTotalHarga();
        hitungDenda();
    }//GEN-LAST:event_txt_total_hargaKeyReleased

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_total_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_hargaActionPerformed

    private void txt_total_dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_dendaActionPerformed
        // TODO add your handling code here:
//        try {
//        double harga = Double.parseDouble(txt_harga.getText().trim());
//        int durasi = Integer.parseInt(txt_durasi_sewa.getText().trim());
//        LocalDate tglPengambilan = LocalDate.parse(txt_tgl_pengambilan.getText().trim());
//        LocalDate tglPengembalian = LocalDate.parse(txt_tgl_pengembalian.getText().trim());
//        
//        LocalDate tglTenggat = tglPengambilan.plusDays(durasi);
//
//        double dendaPerHari = harga * 1.1;
//
//        double totalDenda = 0;
//        if (tglPengembalian.isAfter(tglTenggat)) {
//            long daysLate = ChronoUnit.DAYS.between(tglTenggat, tglPengembalian);
//            totalDenda = daysLate * dendaPerHari;
//        }
//
//        txt_total_denda.setText(String.valueOf(totalDenda));
//
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa kembali input Durasi atau Harga.", "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
    }//GEN-LAST:event_txt_total_dendaActionPerformed

    private void txt_total_dendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_dendaKeyReleased
        // TODO add your handling code here:
        hitungDenda();
    }//GEN-LAST:event_txt_total_dendaKeyReleased

    private void txt_tgl_pengembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tgl_pengembalianKeyReleased
        // TODO add your handling code here:
        hitungDenda();
    }//GEN-LAST:event_txt_tgl_pengembalianKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_peminjaman;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_stok;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_pengembalian;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_durasi_sewa;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_ps;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tgl_pengambilan;
    private javax.swing.JTextField txt_tgl_pengembalian;
    private javax.swing.JTextField txt_total_denda;
    private javax.swing.JTextField txt_total_harga;
    private javax.swing.JTextField txt_waktu_tenggat;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        peminjamCrudService = new ControllerPeminjam(new ConnectionManager());
        List<Peminjam> listPeminjam = peminjamCrudService.findAll();
        Object[][] dataPeminjam = new Object[listPeminjam.size()][12];

        int counter = 0;

        for (Peminjam peminjam : listPeminjam) {
            dataPeminjam[counter][0] = peminjam.getId_Peminjaman(); // ID Peminjaman
            dataPeminjam[counter][1] = peminjam.getNama_Penyewa();  // Nama Penyewa
            dataPeminjam[counter][2] = peminjam.getNo_Telp();       // Nomor Telepon
            dataPeminjam[counter][3] = peminjam.getAlamat();        // Alamat
            dataPeminjam[counter][4] = peminjam.getPs();            // PS
            dataPeminjam[counter][5] = peminjam.getDurasi_Hari();   // Durasi Hari
            dataPeminjam[counter][6] = peminjam.getTgl_Pengambilan(); // Tanggal Pengambilan
            dataPeminjam[counter][7] = peminjam.getTgl_Tenggat();   // Tanggal Tenggat
            dataPeminjam[counter][8] = peminjam.getHarga();   // Total Biaya
            dataPeminjam[counter][9] = peminjam.getTotal_Biaya();   // Total Biaya
            dataPeminjam[counter][10] = peminjam.getTgl_pengembalian();   // Total Biaya
            dataPeminjam[counter][11] = peminjam.getTotal_denda();   // Total Biaya

            counter++;
        }

        table_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
                dataPeminjam,
                new String[]{
                    "ID Peminjaman", "Nama Penyewa", "Nomor Telepon", "Alamat", "PS", "Durasi Hari", "Tanggal Pengambilan", "Tanggal Tenggat", "Harga", "Total Biaya", "Tanggal Pengembalian", "Total Denda" 
                }
        ));
        //table_pengembalian.repaint();
    }

    private String parseString(Object value) {
        return value == null ? "" : value.toString();
    }

    private int parseInteger(Object value) {
        try {
            return value == null ? 0 : Integer.parseInt(value.toString());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private double parseDouble(Object value) {
        try {
            return value == null ? 0 : Double.parseDouble(value.toString());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private void emptyField() {
            txt_nama.setText("");
            txt_notelp.setText("");
            txt_alamat.setText("");
            txt_tgl_pengambilan.setText("");
            txt_durasi_sewa.setText("");
            txt_nama_ps.setText("");
            txt_harga.setText("");
            txt_waktu_tenggat.setText("");
            txt_total_harga.setText("");
            txt_tgl_pengembalian.setText("");
            txt_total_denda.setText("");
        }
    
    private void hitungDenda() {
    try {
        // Ambil input data
        double harga = Double.parseDouble(txt_harga.getText().trim());
        int durasi = Integer.parseInt(txt_durasi_sewa.getText().trim());
        LocalDate tglPengambilan = LocalDate.parse(txt_tgl_pengambilan.getText().trim());
        LocalDate tglPengembalian = LocalDate.parse(txt_tgl_pengembalian.getText().trim());

        // Hitung tanggal tenggat
        LocalDate tglTenggat = tglPengambilan.plusDays(durasi);

        // Hitung denda per hari (harga * 1.1)
        double dendaPerHari = harga * 1.1;

        // Hitung total denda
        double totalDenda = 0;
        if (tglPengembalian.isAfter(tglTenggat)) {
            long daysLate = ChronoUnit.DAYS.between(tglTenggat, tglPengembalian);
            totalDenda = daysLate * dendaPerHari;
        }

        // Tampilkan total denda di txt_total_denda
        txt_total_denda.setText(String.valueOf(totalDenda));

    } catch (NumberFormatException | DateTimeParseException e) {
        txt_total_denda.setText("0");
    }
}

    }
