/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.is.crudproject.viewdbswing;

import java.awt.HeadlessException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.is.crudproject.dbconfig.ConnectionManager;
import org.itenas.is.crudproject.model.Pemilik_ps;
import org.itenas.is.crudproject.services.CrudService;
import org.itenas.is.crudproject.servicesdbimpl.ControllerPeminjam;
import org.itenas.is.crudproject.model.Peminjam;
import org.itenas.is.crudproject.servicesdbimpl.ControllerPs;


/**
 *
 * @author riyann
 */
public class ViewPeminjaman extends javax.swing.JFrame {
    private CrudService<Peminjam> peminjamCrudService;
    ControllerPs conPs = new ControllerPs();
    
    /**
     * Creates new form peminjaman
     */
    public ViewPeminjaman() {
        initComponents();
        setLocationRelativeTo(null);
        getData();
        loadData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Peminjaman = new javax.swing.JTable();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_pengembalian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_peminjaman = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_stok = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_tgl_pengambilan = new javax.swing.JTextField();
        txt_durasi_sewa = new javax.swing.JTextField();
        txt_total_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nama_ps = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(890, 600));

        table_Peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama_penyewa", "No telp", "Alamat", "Ps", "Durasi sewa", "tgl mulai", "tgl tenggat", "harga perhari", "total harga"
            }
        ));
        table_Peminjaman.setRequestFocusEnabled(false);
        table_Peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_PeminjamanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_Peminjaman);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("No. ID");

        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setRequestFocusEnabled(false);

        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });

        btn_stok.setText("Stok Barang");
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_peminjaman.setText("Peminjaman");
        btn_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peminjamanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PEMINJAMAN PS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(btn_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        table_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nama ps", "harga perhari"
            }
        ));
        table_stok.setRequestFocusEnabled(false);
        table_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stokMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_stok);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Nama Penyewa");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("No telp");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("tanggal pengambilan");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("durasi hari sewa");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Total harga");

        txt_durasi_sewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_durasi_sewaKeyReleased(evt);
            }
        });

        txt_total_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_total_hargaKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Jenis Ps");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Nama Ps");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("harga perhari");

        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargaKeyReleased(evt);
            }
        });

        btn_submit.setText("submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_notelp)
                                            .addComponent(txt_nama)
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_durasi_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_tgl_pengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_nama_ps, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tgl_pengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_durasi_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_nama_ps, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        emptyField();
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
         peminjamCrudService = new ControllerPeminjam(new ConnectionManager());

    String id = txt_search.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Peminjaman harus diisi sebelum menghapus data!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            boolean isDeleted = peminjamCrudService.delete(Integer.parseInt(id));
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadData(); 
                emptyField(); 
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus. ID tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String searchId = txt_search.getText().trim();

    if (searchId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Peminjaman tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int idPeminjaman = Integer.parseInt(searchId);

        peminjamCrudService = new ControllerPeminjam(new ConnectionManager());
        Peminjam peminjam = peminjamCrudService.findOne(idPeminjaman); // Cari data berdasarkan ID

        DefaultTableModel tableModel = (DefaultTableModel) table_Peminjaman.getModel();
        tableModel.setRowCount(0); 

        if (peminjam != null) {
            Object[] rowData = {
                peminjam.getId_Peminjaman(),
                peminjam.getNama_Penyewa(),
                peminjam.getNo_Telp(),
                peminjam.getAlamat(),
                peminjam.getPs(),
                peminjam.getDurasi_Hari(),
                peminjam.getTgl_Pengambilan(),
                peminjam.getTgl_Tenggat(),
                peminjam.getHarga(),
                peminjam.getTotal_Biaya()
            };
            tableModel.addRow(rowData); 
        } else {
            JOptionPane.showMessageDialog(this, "Data dengan ID Peminjaman tidak ditemukan!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID Peminjaman harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
        String searchId = txt_search.getText().trim();

    if (searchId.isEmpty()) {
        loadAllData(); 
    } else {
        btn_searchActionPerformed(evt); 
    }
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        // TODO add your handling code here:
        new ViewPengembalian().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
        new ViewStok().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_stokActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new ViewLogIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peminjamanActionPerformed
        // TODO add your handling code here:
        new ViewPeminjaman().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_peminjamanActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
        peminjamCrudService = new ControllerPeminjam(new ConnectionManager());

        String idPeminjamanStr = txt_search.getText().trim();
        if (idPeminjamanStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id_peminjaman;
        try {
            id_peminjaman = Integer.parseInt(idPeminjamanStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Peminjaman harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txt_nama.getText().trim().isEmpty()
                || txt_notelp.getText().trim().isEmpty()
                || txt_alamat.getText().trim().isEmpty()
                || txt_tgl_pengambilan.getText().trim().isEmpty()
                || txt_durasi_sewa.getText().trim().isEmpty()
                || txt_nama_ps.getText().trim().isEmpty()
                || txt_harga.getText().trim().isEmpty()
                || txt_total_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nama = txt_nama.getText().trim();
        String no_telp = txt_notelp.getText().trim();
        String alamat = txt_alamat.getText().trim();
        String ps = txt_nama_ps.getText().trim();
        double harga = Double.parseDouble(txt_harga.getText().trim());
        double total_biaya = Double.parseDouble(txt_total_harga.getText().trim());
        int durasi = Integer.parseInt(txt_durasi_sewa.getText().trim());

        LocalDate tglPengambilan = LocalDate.parse(txt_tgl_pengambilan.getText().trim());
        LocalDate tglTenggat = tglPengambilan.plusDays(durasi);

        Peminjam peminjam = new Peminjam();
        peminjam.setNama_Penyewa(nama);
        peminjam.setNo_Telp(no_telp);
        peminjam.setAlamat(alamat);
        peminjam.setPs(ps);
        peminjam.setDurasi_Hari(durasi);
        peminjam.setTgl_Pengambilan(tglPengambilan.toString());
        peminjam.setTgl_Tenggat(tglTenggat.toString());
        peminjam.setHarga(harga);
        peminjam.setTotal_Biaya(total_biaya);

        peminjamCrudService.update(id_peminjaman, peminjam);

        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadData(); // Memuat ulang data ke tabel
        emptyField(); // Mengosongkan field input
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa kembali input Durasi atau Harga.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
       try {
        // Validasi input data
        if (txt_nama.getText().trim().isEmpty()
                || txt_notelp.getText().trim().isEmpty()
                || txt_alamat.getText().trim().isEmpty()
                || txt_tgl_pengambilan.getText().trim().isEmpty()
                || txt_durasi_sewa.getText().trim().isEmpty()
                || txt_nama_ps.getText().trim().isEmpty()
                || txt_harga.getText().trim().isEmpty()
                || txt_total_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parsing input data
        String nama = txt_nama.getText().trim();
        String no_telp = txt_notelp.getText().trim();
        String alamat = txt_alamat.getText().trim();
        String ps = txt_nama_ps.getText().trim();
        double harga = Double.parseDouble(txt_harga.getText().trim());
        double total_biaya = Double.parseDouble(txt_total_harga.getText().trim());
        int durasi = Integer.parseInt(txt_durasi_sewa.getText().trim());
        String kembali = null;
        double denda = 0;

        // Menggunakan LocalDate untuk tgl_pengambilan dan tgl_tenggat
        LocalDate tglPengambilan = LocalDate.parse(txt_tgl_pengambilan.getText().trim());
        LocalDate tglTenggat = tglPengambilan.plusDays(durasi);

        // Set data ke objek Peminjam
        Peminjam peminjam = new Peminjam();
        peminjam.setNama_Penyewa(nama);
        peminjam.setNo_Telp(no_telp);
        peminjam.setAlamat(alamat);
        peminjam.setPs(ps);
        peminjam.setDurasi_Hari(durasi);
        peminjam.setTgl_Pengambilan(tglPengambilan.toString());
        peminjam.setTgl_Tenggat(tglTenggat.toString());
        peminjam.setHarga(harga);
        peminjam.setTotal_Biaya(total_biaya);
        peminjam.setTgl_pengembalian(kembali);
        peminjam.setTotal_denda(denda);
        

        peminjamCrudService.create(peminjam);
        JOptionPane.showMessageDialog(this, "Barang berhasil disewa", "Success", JOptionPane.INFORMATION_MESSAGE);

        loadData();
        emptyField();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa input Harga atau Total Harga.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal tidak valid! Gunakan format YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
         
    }//GEN-LAST:event_btn_submitActionPerformed

    private void table_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stokMouseClicked
        // TODO add your handling code here:
         int i = table_stok.getSelectedRow();
        
        TableModel model = table_stok.getModel();
        txt_nama_ps.setText(model.getValueAt(i, 0).toString());
        txt_harga.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_table_stokMouseClicked

    private void table_PeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_PeminjamanMouseClicked
        // TODO add your handling code here:
        try {
        // Deklarasi variabel
        String nama_penyewa, alamat, no_telp, tgl_pengambilan, tgl_tenggat, nama_ps;
        double hargaPerHari, total_harga;
        int durasi, id_peminjaman;

        int row = table_Peminjaman.getSelectedRow();
        String Harga = table_Peminjaman.getValueAt(row, 8).toString().replace(",", "");
        String totalHarga = table_Peminjaman.getValueAt(row, 9).toString().replace(",", "");

        id_peminjaman = Integer.parseInt(table_Peminjaman.getValueAt(row, 0).toString());
        nama_penyewa = table_Peminjaman.getValueAt(row, 1).toString();
        no_telp = table_Peminjaman.getValueAt(row, 2).toString();
        alamat = table_Peminjaman.getValueAt(row, 3).toString();
        nama_ps = table_Peminjaman.getValueAt(row, 4).toString();
        durasi = Integer.parseInt(table_Peminjaman.getValueAt(row, 5).toString());
        tgl_pengambilan = table_Peminjaman.getValueAt(row, 6).toString();
        tgl_tenggat = table_Peminjaman.getValueAt(row, 7).toString();
        hargaPerHari = Double.parseDouble(Harga);
        total_harga = Double.parseDouble(totalHarga);

        // Tampilkan nilai pada form dengan format titik untuk desimal
        txt_search.setText(String.valueOf(id_peminjaman));
        txt_search.setEnabled(false);
        txt_nama.setText(nama_penyewa);
        txt_notelp.setText(no_telp);
        txt_alamat.setText(alamat);
        txt_tgl_pengambilan.setText(tgl_pengambilan);
        txt_durasi_sewa.setText(String.valueOf(durasi));
        txt_nama_ps.setText(nama_ps);

        txt_harga.setText(String.format("%.2f", hargaPerHari).replace(',', '.'));
        txt_total_harga.setText(String.format("%.2f", total_harga).replace(',', '.'));
    } catch (Exception e) {
        // Tangani kesalahan jika ada
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
        
    }//GEN-LAST:event_table_PeminjamanMouseClicked

    private void txt_total_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_hargaKeyReleased
        totalHarga();
    }//GEN-LAST:event_txt_total_hargaKeyReleased

    private void txt_durasi_sewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_durasi_sewaKeyReleased
        // TODO add your handling code here:
        totalHarga();
    }//GEN-LAST:event_txt_durasi_sewaKeyReleased

    private void txt_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyReleased
        // TODO add your handling code here:
        totalHarga();
    }//GEN-LAST:event_txt_hargaKeyReleased

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked
        // TODO add your handling code here:
         txt_search.setText("");
         loadAllData();
    }//GEN-LAST:event_txt_searchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_peminjaman;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_stok;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_Peminjaman;
    private javax.swing.JTable table_stok;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_durasi_sewa;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_ps;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tgl_pengambilan;
    private javax.swing.JTextField txt_total_harga;
    // End of variables declaration//GEN-END:variables
private void loadData() {
    peminjamCrudService = new ControllerPeminjam(new ConnectionManager());
    List<Peminjam> listPeminjam = peminjamCrudService.findAll();
    Object[][] dataPeminjam = new Object[listPeminjam.size()][10];

    int counter = 0;

    for (Peminjam peminjam : listPeminjam) {
        dataPeminjam[counter][0] = peminjam.getId_Peminjaman(); 
        dataPeminjam[counter][1] = peminjam.getNama_Penyewa();  
        dataPeminjam[counter][2] = peminjam.getNo_Telp();       
        dataPeminjam[counter][3] = peminjam.getAlamat();        
        dataPeminjam[counter][4] = peminjam.getPs();            
        dataPeminjam[counter][5] = peminjam.getDurasi_Hari();   
        dataPeminjam[counter][6] = peminjam.getTgl_Pengambilan(); 
        dataPeminjam[counter][7] = peminjam.getTgl_Tenggat();   
        dataPeminjam[counter][8] = peminjam.getHarga();   
        dataPeminjam[counter][9] = peminjam.getTotal_Biaya();   
        counter++;
    }

    table_Peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            dataPeminjam,
            new String[]{
                "ID Peminjaman", "Nama Penyewa", "Nomor Telepon", "Alamat", "PS", "Durasi Hari", "Tanggal Pengambilan", "Tanggal Tenggat", "Harga","Total Biaya"
            }
    ));
}

public final void getData() {
        DefaultTableModel dtm = (DefaultTableModel) table_stok.getModel();
        
        dtm.setRowCount(0);
        
        List<Pemilik_ps> listPs = conPs.showPs();
        String[] data = new String[2];
        for (Pemilik_ps newPs : listPs) {
            data[0] = newPs.getNama_ps();
            data[1] = Double.toString(newPs.getHarga());
            dtm.addRow(data);
        }
    }

    private void emptyField() {
        txt_nama.setText("");
        txt_notelp.setText("");
        txt_alamat.setText("");
        txt_tgl_pengambilan.setText("");
        txt_durasi_sewa.setText("");
        txt_nama_ps.setText("");
        txt_harga.setText("");
        txt_total_harga.setText("");
        
    }
    
        private void totalHarga() {
        try {
            String durasiText = txt_durasi_sewa.getText().trim();
            String hargaText = txt_harga.getText().trim().replace(",", ""); // Menghilangkan koma jika ada

            if (!durasiText.isEmpty() && !hargaText.isEmpty()) {
                int durasi = Integer.parseInt(durasiText);
                double hargaPerHari = Double.parseDouble(hargaText);  // Menggunakan double untuk harga yang lebih presisi

                double totalHarga = durasi * hargaPerHari;

                txt_total_harga.setText(String.format("%.2f", totalHarga).replace(",", ".")); // Format dengan 2 angka desimal dan ganti koma dengan titik
            }
        } catch (NumberFormatException e) {
            txt_total_harga.setText("0.0");
        }
    }
        
        private void loadAllData() {
    try {
        peminjamCrudService = new ControllerPeminjam(new ConnectionManager());
        List<Peminjam> listPeminjam = peminjamCrudService.findAll(); // Mendapatkan semua data

        DefaultTableModel tableModel = (DefaultTableModel) table_Peminjaman.getModel();
        tableModel.setRowCount(0); // Hapus data lama

        for (Peminjam peminjam : listPeminjam) {
            Object[] rowData = {
                peminjam.getId_Peminjaman(),
                peminjam.getNama_Penyewa(),
                peminjam.getNo_Telp(),
                peminjam.getAlamat(),
                peminjam.getPs(),
                peminjam.getDurasi_Hari(),
                peminjam.getTgl_Pengambilan(),
                peminjam.getTgl_Tenggat(),
                peminjam.getHarga(),
                peminjam.getTotal_Biaya()
            };
            tableModel.addRow(rowData); 
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


}
